name: CD_pipeline
on:
  workflow_run:
    workflows: ["CI pipeline"]
    types:
      - completed

  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/your-app-name:latest .
      - name: Push Docker image to registry
        run: docker push ${{ secrets.DOCKER_USERNAME }}/your-app-name:latest
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Install Homebrew (if not already installed)
        run: |
           if ! which brew >/dev/null; then
              /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
           fi
      - name: Tap render-oss repository
        run: brew tap render-oss/render
      - name: Install render CLI
        run: brew install render
      - name: Login to Render
        run: render login ${{ secrets.RENDER_API_KEY }}
      - name: Deploy to Render
        run: render deploy ${{ secrets.RENDER_SERVICE_ID }} -f dockerfile:Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/your-app-name:latest
