name: CD_pipeline
on:
  workflow_run:
    workflows: ["CI pipeline"]
    types:
      - completed

  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/your-app-name:latest .
      - name: Push Docker image to registry
        run: docker push ${{ secrets.DOCKER_USERNAME }}/your-app-name:latest
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Download Render CLI
        uses: rendr/render-cli@v1.4.1
        with:
          token: ${{ secrets.RENDER_API_KEY }}
      - name: Login to Render
        run: render login ${{ secrets.RENDER_API_KEY }}
      - name: Deploy to Render
        run: render deploy ${{ secrets.RENDER_SERVICE_ID }} -f dockerfile:Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/your-app-name:latest
